language: ruby
before_install:
  - gem update bundler --no-document
before_script:
  - psql -c 'create database queue_classic_test;' -U postgres
env:
  global:
    - QC_DATABASE_URL="postgres://postgres@localhost/queue_classic_test"
    - QC_BENCHMARK=true
    - QC_BENCHMARK_MAX_TIME_DEQUEUE=60
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.10
  - 2.1.0
  - 2.0.0
  - 1.9.3
addons:
  postgresql: 9.3
